services:
  db:
    image: postgres:18.1
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: just_notes
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    restart: always

  application:
    image: just-notes
    container_name: just-notes
    ports:
      - "80:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/just_notes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    restart: always

volumes:
  pg_data:
